Run linux-cmake tests in a smaller environment
Kart is having trouble forking subprocesses in the Linux-CMake job:

```
OSError: [Errno 7] Argument list too long: ‘git’
```

Since the argument list is actually pretty short, a working theory is
that os.environ is too large.

This change adjusts the job to clear the environment out before running
pytest, to see if that helps the tests pass